---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:stable
  amd64: ghcr.io/hassio-addons/ubuntu-base:stable
codenotary:
  base_image: notary@home-assistant.io
  signer: andrewjswan@addons.community
